### ISSUE TITLE
Use for detection

### ISSUE THREAD

**Issue by chenbinghui1** [GothicAi/InstaBoost-pypi#12]
Can I use it for only detection? I tested it by using get_new_data without 'segmentation' keywords, and it failed. So what can i do so as to use the codes for only detection.

**Comment by rogerwwww** [comment]
Hi there,

Our experiments show that: If you use our method for detection data where segmentation masks are not available, the performance may not be satisfying. Thus, we only support data with segmentation masks.

**Comment by chenbinghui1** [comment]
@rogerwwww  Thanks for your reply! I got it.
