### ISSUE TITLE
global_matting has no effect

### ISSUE THREAD

**Issue by qianyizhang** [GothicAi/InstaBoost-pypi#3]
i randomly process 50 coco examples with get_instance_group.extract() and default config step by step
it seems global_matting does not have ANY effect to the image, does it make sense?

i make the following change after line 173
https://github.com/GothicAi/InstaBoost-pypi/blob/master/instaboost/get_instance_group.py#L173
```python
res =alphamapi-maskgroupi*255
print(res.max())
```

**Comment by Fang-Haoshu** [comment]
Hi, can you save the processed image and see the results?

**Comment by qianyizhang** [comment]
what do you mean.
it's not an empty image, but pretty much the same as 
```python
mask = trimapi>0
alphamapi = 255 * mask 
```
so I wonder if that's due to the default config, or something wrong with the opencv_mat?

**Comment by Fang-Haoshu** [comment]
After using 
```
new_ann, new_img = get_new_data(ori_anns: list, 
                                ori_img: np.ndarray, 
                                config: InstaBoostConfig, 
                                background: np.ndarray)
```
you can get a new image, can you post some images here? We can check these new images to see if opencv_mat has effect

**Comment by qianyizhang** [comment]
sorry for the delay, got caught up with works.
heres a link for 3 sets of images, each processed by get_new_data with default config, where the original one is imageid_orig.jpeg (taken from coco2017)

https://postimg.cc/gallery/1shiasqt0/

hope this helps.
happy moon-cake festival :P,

**Comment by Fang-Haoshu** [comment]
Haha thanks, happy moon-cake festival :P.
I checked the images you generated, the matting is fine:D

Have fun!
