### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zieitokk** [GothicAi/InstaBoost-pypi#4]
Hi, may I ask two questions:
1. The heatmap that generated at `Line. 111` in `pointByHeatmap.py` has shape (oriHeight x oriWidth) with all entries are zeros. And when it goes to be "normalized", most of the zeros in heatmap turn into 255, which represent high consistencies. But those zeros should no way be 255 in consistency heatmap. Would you mind checking it for me?

2. In your paper, the heatpoints are calculated every pixels in one image. However, there are multiple boolean multiplication at `Line. 85` in `help_functions.py`, and this prevents those augmented rings from being outside of background's boundary. So this should return a restricted heatmap with margin pixels are not being calculated. So my question is, how did you generate a full heatmap with every pixels are calculated? 

Thank you very much!

**Comment by GothicAi** [comment]
Hi, for question 1, `img.shape` in `Line. 111` in `pointByHeatmap.py` is resized shape, and all zeros will have new value after heatmap generation in `Line 115`-`Line 120`; for question 2, our paper has illustrated this as an exception at the end of page 4, and in our experiments, we found that the value in boundaries is usually small, thus we ignore this for acceleration.

**Comment by zieitokk** [comment]
> Hi, for question 1, `img.shape` in `Line. 111` in `pointByHeatmap.py` is resized shape, and all zeros will have new value after heatmap generation in `Line 115`-`Line 120`; for question 2, our paper has illustrated this as an exception at the end of page 4, and in our experiments, we found that the value in boundaries is usually small, thus we ignore this for acceleration.

Oh, I get it. Thank you very much!
