### ISSUE TITLE
How much time get_new_data() spend on deal with one single image? 

### ISSUE THREAD

**Issue by brook-cheng** [GothicAi/InstaBoost-pypi#7]
Hi,i want to know the function get_new_data() spend how much time on processing one single image in your compute.In my test, it takes 0.75s to processing one single image(1280x675,3 channels) with one "segementation".And are there any ways to imporve get_new_data() processing speed?

**Comment by Fang-Haoshu** [comment]
I guess 0.75s is a reasonable number. To speed up, you can use multiple worker to parallelize the process. That's why we wrap it as a dataloader. We recommend the worker of dataloader 2 times larger than the batch size.

**Comment by brook-cheng** [comment]
> I guess 0.75s is a reasonable number. To speed up, you can use multiple worker to parallelize the process. That's why we wrap it as a dataloader. We recommend the worker of dataloader 2 times larger than the batch size.

Thanks.And i find an interesting thing cv2.filter2D is faster than ndimage.convolve.
In gettrimap(mask,k), ndimage.convolve cost 0.1998s per image which almost take 1/3 time in total time.So i replace ndimage.convolve with cv2.filter2D which cost 0.0316s per image. Maybe that's a good idear to speed up the function.

**Comment by Fang-Haoshu** [comment]
Oh wow! Thanks! We will take a look!
